package br.ufsc.src.igu;

public enum EnumMenuOption {
	OPTIONCONECTION, 
	OPTIONOPENDSV,
	OPTIONOPEN,
	OPTIONDBROKETRAJECTORY,
	OPTIONREMOVENOISE,
	OPTIONEXPORTCSV,
	OPTIONTRAJNEARPOINT,
	TEST,
	OPTIONDBROKETRAJECTORY1
}